### ISSUE TITLE
bot starts fishing when i start recording

### ISSUE THREAD

**Issue by Ronso20** [fishyboteso/fishyboteso#82] opened 2021-05-20 22:05 UTC
The bot starts fishing when i start recording and i'm looking at fishing hole at that moment.

**Comment by adsau59** [comment] 2021-05-22 01:17
not able to reproduce this issue, do you have any steps to reproduce this issue?

**Comment by Ronso20** [comment] 2021-05-22 08:29
https://youtu.be/nfq1ucca-Y8

But, it's not really a big problem, i can just look away and then start recording.

**Comment by adsau59** [comment] 2022-02-03 01:57
fixed in v0.5.7

**Closed by adsau59** 2022-02-03 01:57 UTC
Labels: bug, Fullauto
